Tile ghost tint customization
raiguard/TintedGhosts pull request #3
Opened 2023-10-27 10:55 UTC by setazer

2023-12-20 05:16 UTC, raiguard commented
Thanks!

2023-12-20 05:19 UTC, raiguard requested changes
Thanks! Just a few things.

2023-12-20 05:19 UTC, raiguard commented on changelog.txt
> +Version: 1.0.3
Please move the changelog to the 1.0.2 entry and keep the date as unknown. My publishing workflow will insert the date and bump the version numbers automatically.

2023-12-20 05:19 UTC, raiguard commented on info.json
> +  "version": "1.0.3",
Please revert this to 1.0.2, as that is the current development version.

2023-12-20 05:19 UTC, raiguard commented on settings.lua
> +    default_value = {r = 0.3, g = 0.6, b = 0.6, a = 0.3},
I prefer the old default tint, please change it back.

2024-01-12 15:58 UTC, closed without merging

2024-01-12 15:58 UTC, setazer commented
gonna reopen this PR with proper flow